apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 105506694521.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:05b084f3bf4ef9092de3bcb0c3a471b34a64ced6
        ports:
        - containerPort: 80
