apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 105506694521.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:e4ddb33509455d8cd56966bba8409c1d1a8c6206
        ports:
        - containerPort: 80
