apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 105506694521.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:05b084f3bf4ef9092de3bcb0c3a471b34a64ced6
        ports:
        - containerPort: 80
