apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 995673420677.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:7cf843d093db2255002786eae3df1b13a2ec210f
        ports:
        - containerPort: 80
