apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 105506694521.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:f1f952e4aa0b7376cccde32c382ba20a35e141aa
        ports:
        - containerPort: 80
